version: "3.7"
services:
    external-service:
        image: openjdk:11
        volumes:
            - ./external-service:/usr/src/myapp 
        command: bash -c "./gradlew :external-service:bootRun"
        restart: always
        ports:
            - 3004:3004
    backend:
        build: .
        restart: always
        ports:
            - 8080:8080
        volumes:
            - .:/backend          
        command: ./gradlew :backend:bootRun
        depends_on:
            - postgres_db
        links:
            - postgres_db:database

    postgres_db:
        image: "postgres"
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: java_to_dev_app_db
            POSTGRES_PASSWORD: nE5kMc7JCGNqwDQM
        